### ISSUE TITLE
Echidna Docker Versioning

### ISSUE THREAD

**Issue by naszam** [crytic/echidna-action#2]
Hi @elopez,

I've recently opened a pr to use the echidna action:
https://github.com/makerdao/dss-vest/pull/45
I've noticed that the echidna action fetches the latest [docker build](https://hub.docker.com/r/trailofbits/echidna/) on [master](https://github.com/crytic/echidna/runs/4691571753?check_suite_focus=true).
I'd like to know if would be possible to point to a stable version by default and add a key to specify a tagged release version (including `latest` to point at master branch in case of latest fixes and features).
Thanks!

**Comment by elopez** [comment]
Thanks for the feature request! I agree it would be nice to have.

Unfortunately it looks like it's not as direct to implement version changing at this time: https://github.community/t/feature-request-build-args-support-in-docker-container-actions/16846

I'll look at other possible ways to implement this.

**Comment by elopez** [comment]
Hi @naszam. I have opened a draft PR with a possible approach for this. If you want to try it out, you can experiment with `using: crytic/echidna-action@dev-echidna-version` and the new `echidna-version` input, which takes one of the [Docker tags from `trailofbits/echidna`](https://hub.docker.com/r/trailofbits/echidna/tags)

**Comment by naszam** [comment]
Hi @elopez,
I've tried the new action input key, specifying `v1.7.3` and it worked :tada:
```
Step 1/6 : ARG ECHIDNA_TAG=latest
Step 2/6 : FROM trailofbits/echidna:$ECHIDNA_TAG
v1.7.3: Pulling from trailofbits/echidna
```
Also, glanced at the current approach and lgtm.
Thanks!

**Comment by elopez** [comment]
I'm closing this as #3 is now merged. The feature will be released with the next action version 🎉
